#!/bin/bash

allow_push=$( python3 -m main get allow-push )
git_user=alanmatzumiya
username=circuitalmynds
repo=music_z5

echo *__pycache__ > .gitignore
find ./videos* -size +95M | cat >> .gitignore
if $allow_push; then

    python3 -m getdata
    python3 -m main set allow-push false

    git add .
    git commit -m "autocommit"
    git push https://$git_user:"$( head "$HOME"/secret )"@github.com/$username/$repo.git

fi